/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skipbogame;

/**
 *
 * @author fa248289
 */
public class SkipBo extends javax.swing.JFrame {

    /**
     * Creates new form SkipBo
     */
    public SkipBo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CardLabel1 = new javax.swing.JLabel();
        CardLabel2 = new javax.swing.JLabel();
        CardLabel3 = new javax.swing.JLabel();
        CardLabel4 = new javax.swing.JLabel();
        CardLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DP1B = new javax.swing.JButton();
        DP2B = new javax.swing.JButton();
        DP3B = new javax.swing.JButton();
        DP4B = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        C1B = new javax.swing.JButton();
        C2B = new javax.swing.JButton();
        C3B = new javax.swing.JButton();
        C4B = new javax.swing.JButton();
        C5B = new javax.swing.JButton();
        DrawButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        P1B = new javax.swing.JButton();
        P2B = new javax.swing.JButton();
        P3B = new javax.swing.JButton();
        P4B = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Skip Bo");

        CardLabel1.setText("Card1");

        CardLabel2.setText("Card2");

        CardLabel3.setText("Card3");

        CardLabel4.setText("Card4");

        CardLabel5.setText("Card5");

        jLabel8.setText("Opponent Cards");

        DP1B.setText("Discard");
        DP1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DP1BActionPerformed(evt);
            }
        });

        DP2B.setText("Discard");
        DP2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DP2BActionPerformed(evt);
            }
        });

        DP3B.setText("Discard");
        DP3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DP3BActionPerformed(evt);
            }
        });

        DP4B.setText("Discard");
        DP4B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DP4BActionPerformed(evt);
            }
        });

        jLabel9.setText("Discard1");

        jLabel10.setText("Discard2");

        jLabel11.setText("Discard3");

        jLabel12.setText("Discard4");

        C1B.setText("^");

        C2B.setText("^");

        C3B.setText("^");

        C4B.setText("^");

        C5B.setText("^");

        DrawButton.setText("Draw");
        DrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrawButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("  ");

        jLabel14.setText("          ");

        jLabel15.setText("          ");

        jLabel16.setText("          ");

        P1B.setText("^");

        P2B.setText("^");

        P3B.setText("^");

        P4B.setText("^");

        jLabel17.setText("Discard3");

        jLabel18.setText("Discard4");

        jLabel19.setText("Discard1");

        jLabel20.setText("Discard2");

        jLabel21.setText("Opponent Discard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(31, 31, 31)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CardLabel1)
                            .addComponent(C1B))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CardLabel2)
                            .addComponent(C2B))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C3B)
                            .addComponent(CardLabel3))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C4B)
                            .addComponent(CardLabel4))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1)
                            .addGap(148, 148, 148)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(107, 107, 107)
                            .addComponent(DP1B)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(DP2B)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DP3B)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DP4B))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(jLabel9)
                            .addGap(39, 39, 39)
                            .addComponent(jLabel10)
                            .addGap(37, 37, 37)
                            .addComponent(jLabel11)
                            .addGap(34, 34, 34)
                            .addComponent(jLabel12))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(DrawButton)
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(P1B)
                                    .addGap(22, 22, 22)
                                    .addComponent(P2B)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(P4B))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel14)
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(P3B)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(jLabel15)))
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel16)
                                    .addGap(4, 4, 4))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C5B)
                    .addComponent(CardLabel5))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DrawButton)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P4B)
                    .addComponent(P3B)
                    .addComponent(P2B)
                    .addComponent(P1B))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DP1B, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DP2B, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DP3B, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DP4B, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CardLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C2B)
                            .addComponent(C3B)
                            .addComponent(C4B)
                            .addComponent(C5B)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CardLabel1)
                            .addComponent(CardLabel2)
                            .addComponent(CardLabel3)
                            .addComponent(CardLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C1B)))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Deck deck1 = new Deck(4);

    int[]someHand = new int[5];
    for (int i = 1; i<5; i++){
        someHand [i] = deck1.generateCard();
    }
    int[]someNum = new int [13];
      //CF = Card Face and CN = Card Number  
    String CF1 = deck1.getFace(someHand[0]%13);
    String CN1 = deck1.getSuit(someNum[0]/13);
    CardLabel1.setText(CF1 +" of " + CN1);
    String CF2 = deck1.getFace(someHand[0]%13);
    String CN2 = deck1.getSuit(someNum[0]/13);
        CardLabel1.setText(CF1 +" of " + CN1);
    String CF3 = deck1.getFace(someHand[0]%13);
    String CN3 = deck1.getSuit(someNum[0]/13);
        CardLabel1.setText(CF1 +" of " + CN1);
    String CF4 = deck1.getFace(someHand[0]%13);
    String CN4 = deck1.getSuit(someNum[0]/13);
       CardLabel1.setText(CF1 +" of " + CN1);
    String CF5 = deck1.getFace(someHand[0]%13);
    String CN5 = deck1.getSuit(someNum[0]/13);
        CardLabel1.setText(CF1 +" of " + CN1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DP1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DP1BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DP1BActionPerformed

    private void DP2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DP2BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DP2BActionPerformed

    private void DP3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DP3BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DP3BActionPerformed

    private void DP4BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DP4BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DP4BActionPerformed

    private void DrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrawButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrawButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkipBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkipBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkipBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkipBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SkipBo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C1B;
    private javax.swing.JButton C2B;
    private javax.swing.JButton C3B;
    private javax.swing.JButton C4B;
    private javax.swing.JButton C5B;
    private javax.swing.JLabel CardLabel1;
    private javax.swing.JLabel CardLabel2;
    private javax.swing.JLabel CardLabel3;
    private javax.swing.JLabel CardLabel4;
    private javax.swing.JLabel CardLabel5;
    private javax.swing.JButton DP1B;
    private javax.swing.JButton DP2B;
    private javax.swing.JButton DP3B;
    private javax.swing.JButton DP4B;
    private javax.swing.JButton DrawButton;
    private javax.swing.JButton P1B;
    private javax.swing.JButton P2B;
    private javax.swing.JButton P3B;
    private javax.swing.JButton P4B;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
